install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- kpsepath tex
- kpsewhich cRussian.sty
- mkdir _build
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex -output-directory _build ./algebra/algebra1.tex
deploy:
    provider: pages
    skip_cleanup: true
    repo: gt22/hse-lecture-notes-pages
    target_branch: master
    local_dir: _build
