before_install:
    - sudo apt-get -y install texlive texlive-lang-cyrillic texlive-xetex texlive-generic-extra texlive-fonts-extra texlive-science fonts-cmu fonts-lmodern 
script:
- pyenv global 3.7
- python3 ./build.py
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    repo: gt22/hse-lecture-notes-pages
    target_branch: new_conspects
    local_dir: pdf
