install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- mkdir _build
# Prefix command with travis_wait x so it times out after 3 mins
- ls /tmp/texlive/texmf-local
- kpsepath tex 
- travis_wait 3 pdflatex -output-directory _build ./algebra/algebra1.tex
