install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- pyenv global 3.7
- kpsepath tex
- kpsewhich cRussian.sty
- mkdir _build
- python3 ./texlive/build_all.py
- source ./texlive/cleanup.sh
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    repo: gt22/hse-lecture-notes-pages
    target_branch: master
    local_dir: _build
